const items = [
    {
      id: '1',
      title: 'The Enchanted Forest',
      description: 'Explore the mystical forest where magic awaits at every turn.',
      voteCount: 10,
      level: 'Medium',
      category: 'Sci-Fi',
    },
    {
      id: '2',
      title: 'Lost in Time',
      description: 'Embark on a time-traveling adventure to rewrite history itself.',
      voteCount: 5,
      level: 'Easy',
      category: 'Action',
    },
    {
      id: '3',
      title: 'Whispers of the Past',
      description: 'Uncover the long-forgotten secrets of an ancient civilization.',
      voteCount: 8,
      level: 'Hard',
      category: 'Drama',
    },
    {
      id: '4',
      title: 'Mystery at Midnight Manor',
      description: 'Solve puzzles and riddles to reveal the dark secrets of Midnight Manor.',
      voteCount: 15,
      level: 'Medium',
      category: 'Mystery',
    },
    {
      id: '5',
      title: 'A Love Beyond Time',
      description: 'A romantic journey that defies the boundaries of time and space.',
      voteCount: 3,
      level: 'Easy',
      category: 'Romance',
    },
    {
      id: '6',
      title: 'Realm of the Cosmic Warriors',
      description: 'Become a cosmic warrior and battle interstellar forces in this epic adventure.',
      voteCount: 12,
      level: 'Hard',
      category: 'Action',
    },
    {
      id: '7',
      title: 'The Forgotten Symphony',
      description: 'Unearth the lost melodies and harmonies of a forgotten musical masterpiece.',
      voteCount: 6,
      level: 'Medium',
      category: 'Drama',
    },
    {
      id: '8',
      title: 'The Haunting of Hollow House',
      description: 'Face your deepest fears as you navigate the eerie corridors of Hollow House.',
      voteCount: 9,
      level: 'Easy',
      category: 'Horror',
    },
    {
      id: '9',
      title: 'Quest for the Elixir of Immortality',
      description: 'Embark on a perilous quest to discover the legendary elixir of eternal life.',
      voteCount: 20,
      level: 'Hard',
      category: 'Sci-Fi',
    },
    {
      id: '10',
      title: 'Secrets of the Timeless Scroll',
      description: 'Unlock the secrets of a mysterious scroll that holds the key to ultimate power.',
      voteCount: 7,
      level: 'Medium',
      category: 'Horror',
    },
    {
        id: '11',
        title: 'Some Love story in park',
        description: 'Write some description after you read dialog',
        voteCount: 18,
        level: 'Medium',
        category: 'Romance',
      },
  ];
  
  export default items;
  