const items = [
    {
      id: '1',
      title: 'The Enchanted Forest',
      description: 'Explore the mystical forest where magic awaits at every turn.',
      voteCount: 10,
      level: 'Medium',
      category: 'Sci-Fi',
    },
    {
      id: '2',
      title: 'Детские игры и праздники',
      description: 'Воспоминания о детстве, играх и татарских праздниках.',
      voteCount: 19,
      level: 'Easy',
      category: 'Action',
    },
    {
      id: '3',
      title: 'Сказки и легенды татар',
      description: 'Рассказы о татарских сказках и мифах.',
      voteCount: 18,
      level: 'Hard',
      category: 'Drama',
    },
    {
      id: '4',
      title: 'Вкус татарской кухни',
      description: 'Рецепты и кулинарные секреты в татарской кухне.',
      voteCount: 17,
      level: 'Medium',
      category: 'Mystery',
    },
    {
      id: '5',
      title: 'Святым местам посвящено',
      description: 'Путешествие к святым местам и духовным традициям.',
      voteCount: 16,
      level: 'Easy',
      category: 'Romance',
    },
    {
      id: '6',
      title: 'Жизнь в юрте',
      description: 'Рассказ о повседневной жизни татар в традиционных юртах.',
      voteCount: 12,
      level: 'Hard',
      category: 'Action',
    },
    {
      id: '7',
      title: 'Ярмарка: Прошлое и настоящее',
      description: 'История татарских ярмарок и торговых традиций.',
      voteCount: 6,
      level: 'Medium',
      category: 'Drama',
    },
    {
      id: '8',
      title: 'Мой татарский язык',
      description: 'История о значении изучения татарского языка для личной идентичности.',
      voteCount: 9,
      level: 'Easy',
      category: 'Horror',
    },
    {
      id: '9',
      title: 'Quest for the Elixir of Immortality',
      description: 'Embark on a perilous quest to discover the legendary elixir of eternal life.',
      voteCount: 20,
      level: 'Hard',
      category: 'Sci-Fi',
    },
    {
      id: '10',
      title: 'Мудрость дедушки',
      description: 'Мудрость дедушки',
      voteCount: 7,
      level: 'Medium',
      category: 'Horror',
    },
  ];
  
  export default items;
  